/* ACTIVITY 1 */
CREATE TABLE IF NOT EXISTS PRODUCTS(
    PRODUCT_ID TEXT PRIMARY KEY,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);

INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE) VALUES
('01','PHONE','S01','C03','10',7000),
('02','DESKTOP','S02','C01','15',14000),
('03','EARPHONES','S03','C07','30',250),
('04','LAPTOP','S04','C11','10',10000),
('05','MOUSE','S05','C09','11',750);

SELECT COUNT(PRODUCT_ID) FROM PRODUCTS;

SELECT AVG(PRICE) FROM PRODUCTS;

SELECT SUM(PRICE) FROM PRODUCTS;

SELECT * FROM PRODUCTS
WHERE UNIT>10 AND PRICE>1000;

SELECT * FROM ORDERS;

SELECT SUM(AMOUNT) FROM ORDERS
WHERE AMOUNT>1000;

SELECT SUM(QUANTITY) FROM ORDERS;

SELECT AVG(AMOUNT) FROM ORDERS;
/* ACTIVITY 2 */
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_ID TEXT PRIMARY KEY,
    CUSTOMER_ID TEXT,
    ORDER_NAME TEXT,
    QUANTITY INTEGER,
    STATUS TEXT,
    AMOUNT REAL
);

INSERT INTO ORDERS(ORDER_ID,CUSTOMER_ID,ORDER_NAME,QUANTITY,STATUS,AMOUNT) VALUES
('S01','C08','BATTERIES',100,'PACKAGED',1800),
('S02','C17','COTTON PADS',1,'SHIPPING',50),
('S03','C20','TABLET',5,'ORDER RECIEVED',10000),
('S04','C19','MOUSE',20,'PACKAGED',1500),
('S05','C70','DESKTOP',190,'ORDER RECIEVED',35673);

SELECT * FROM ORDERS
WHERE STATUS='PACKAGED';

SELECT ORDER_NAME FROM ORDERS
WHERE ORDER_NAME LIKE('T%');

SELECT ORDER_NAME FROM ORDERS
WHERE ORDER_NAME LIKE('%S');

SELECT ORDER_NAME FROM ORDERS
WHERE ORDER_NAME LIKE('%TO%');

SELECT ORDER_NAME FROM ORDERS
WHERE ORDER_NAME LIKE('M%E');

SELECT * FROM ORDERS
WHERE STATUS='PACKAGED' AND AMOUNT>1000;